set style line 1 lt 1    lc rgb "blue" lw 5 
set style line 2 lt 2 dt 2 lc rgb "red"  lw 5 
set style line 3 lt 3 dt 3 lc rgb "blue" lw 5 
set style line 4 lt 4 dt 4 lc rgb "red"  lw 3 
set style line 5 lt 5 dt 5 lc rgb "black" lw 3 
set style line 6 lt 6 dt 6 lc rgb "red" lw 3 
set style line 7 lt 7 dt 7 lc rgb "blue" lw 3 
set style line 8 lt 8 dt 8 lc rgb "blue" lw 3 

#used in the rw_timeline plot
set style line 101 lt 1  lc rgb "blue"  lw 5 pt 1 ps 2
set style line 102 lt 1  lc rgb "red"   lw 5 pt 2 ps 2
set style line 103 lt 1  lc rgb "black" lw 5 pt 3 ps 2


set style line 1001 lt 1  lc rgb "blue"  lw 5 pt 1 ps 2
set style line 1002 lt 1  lc rgb "red"   lw 5 pt 2 ps 2
set style line 1003 lt 1  lc rgb "black"  lw 1 pt 3 ps 1

set style line 300  linewidth 1.000 pointtype 2 dashtype 1 pointsize default pointinterval 0

#Use these styles for histograms
set style line 1101 lt 1 lc rgb "#e66101" linewidth 1 pt 3  ps 2 dashtype 1
set style line 1102 lt 1 lc rgb "#fdb863" linewidth 1 pt 5  ps 2 dashtype 1
set style line 1103 lt 1 lc rgb "#b2abd2" linewidth 1 pt 7  ps 2 dashtype 1
set style line 1104 lt 1 lc rgb "#5e3c99" linewidth 1 pt 6  ps 2 dashtype 1
set style line 1105 lt 1 lc rgb "#b35806" linewidth 1 pt 11 ps 2 dashtype 1
set style line 1106 lt 1 lc rgb "#fee0b6" linewidth 1 pt 11 ps 2 dashtype 1

#AWS
set style line 2101 lt 1 lc rgb "#e66101" linewidth 3 pt 6  ps 2 dashtype 1 
#AZURE
set style line 2102 lt 1 lc rgb "#fdb863" linewidth 3 pt 5  ps 2 dashtype 1
#Google
set style line 2103 lt 1 lc rgb "#b2abd2" linewidth 3 pt 7  ps 2 dashtype 1
#IBM
set style line 2104 lt 1 lc rgb "#5e3c99" linewidth 3 pt 3  ps 2 dashtype 1
#
set style line 2105 lt 1 lc rgb "#fee0b6" linewidth 3 pt 11 ps 2 dashtype 1
set style line 2106 lt 1 lc rgb "#d8daeb" linewidth 3 pt 12 ps 2 dashtype 1

#b35806
#f1a340
#fee0b6
#f7f7f7
#d8daeb
#998ec3
#542788
