{
 "title": "Generic (grouped by cloud provicer)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "test",
    "label": "Test",
    "query": "latency, factors, memory, filesystem, custom"
   },
   {
    "name": "testName",
    "label": "Test Name",
    "query": "SHOW TAG VALUES ON \"results\" FROM $test WITH KEY = \"test\";"
   },
   {
    "name": "datapoints",
    "label": "Datapoints Interval",
    "query": "1s,5s,10s,20s,30s,1m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "$test AWS",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "Node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Python",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Go",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": ".NET",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests AWS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'aws' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$test Azure",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "Node (Linux)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Python (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": ".NET (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Node (Windows)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": ".NET (Windows)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests Azure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE  provider =~ /azure/ and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests AWS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'aws' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests Azure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider  =~ /azure/ and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests AWS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'aws' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests Azure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider  =~ /azure/ and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$test Google",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "Node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Python",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Go",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": ".NET",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests Google",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'google' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$test IBM",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "Node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Python",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Go",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": ".NET",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests IBM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'ibm' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests Google",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'google' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests IBM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'ibm' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests Google",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'google' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests IBM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE provider = 'ibm' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}