{
 "title": "Generic (grouped by programming language)",
 "time": { "from": "2019-10-04T08:08:28.288Z", "to": "2019-10-04T08:09:47.767Z" },
 "templating": {
  "list": [
   {
    "name": "test",
    "label": "Test",
    "query": "latency, factors, memory, filesystem, custom"
   },
   {
    "name": "testName",
    "label": "Test Name",
    "query": "SHOW TAG VALUES ON \"results\" from \"$test\" WITH KEY = \"test\";"
   },
   {
    "name": "datapoints",
    "label": "Datapoints Interval",
    "query": "1s,2s,5s,10s,20s,30s,1m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "$test Node",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "AWS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM $test WHERE (\"provider\" = 'aws' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Windows)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Google",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "IBM",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'node' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "ibm" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'node' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$test Python",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "AWS",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Windows)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Google",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "IBM",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'python' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "ibm" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests Python",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'python' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'node' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests Python",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'python' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'node' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests Python",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'python' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$latency Go",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "AWS",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "go" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "go" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Windows)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "go" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Google",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "go" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "IBM",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'go' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "ibm" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "go" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests Go",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'go' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$test .NET",
   "type": "graph",
   "description": "This is the total time the request had until it got back an answer from the function.",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "alias": "AWS",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'aws' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "aws" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "dotnet" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Linux)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azure' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azure" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "dotnet" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Azure (Windows)",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'azureWindows' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "azureWindows" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "dotnet" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "Google",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'google' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "google" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "dotnet" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    },
    {
     "alias": "IBM",
     "measurement": "latency",
     "query": "SELECT mean(\"ms\") FROM \"$test\" WHERE (\"provider\" = 'ibm' AND \"language\" = 'dotnet' AND \"test\" =~ /^$testName$/) AND $timeFilter GROUP BY time($datapoints) fill(linear)",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "ibm" },
      { "condition": "AND", "key": "language", "operator": "=", "value": "dotnet" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$testName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests .NET",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'dotnet' and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests Go",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'go' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Requests .NET",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'dotnet' and success = True and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests Go",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'go' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests .NET",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"$test\" WHERE language = 'dotnet' and success = false and test = '$testName'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}